// rebuild_sr_renderer.js — استبدال بلوك الأي فريم بمنطق Native كامل
const fs = require("fs");
let s = fs.readFileSync("src/renderer.js", "utf8");

const startMarker = "// ═══════════════ Song Requests — أي فريم لوحة التحكم + لينك أوفرلاي الموسيقى ═══════════════";
const start = s.indexOf(startMarker);
if (start === -1) { console.log("old block not found"); process.exit(1); }

const block = [
  "// ═══════════════ Song Requests — Native control page (English) ═══════════════",
  "(function () {",
  '  if (!document.getElementById("page-songs")) return;',
  '  const $ = (id) => document.getElementById(id);',
  "  let srPoll = null;",
  "  let srState = { current: null, queue: [] };",
  "",
  "  function esc(s) { const d = document.createElement('div'); d.textContent = s == null ? '' : String(s); return d.innerHTML; }",
  "  function fmt(ms) { const sec = Math.max(0, Math.round(ms / 1000)); return Math.floor(sec / 60) + ':' + ('0' + (sec % 60)).slice(-2); }",
  "",
  "  async function srReq(method, path, body) {",
  "    try { return await api.sr.request(method, path, body); } catch (e) { return { ok: false, error: e.message }; }",
  "  }",
  "",
  "  function renderQueue(st) {",
  "    const list = $('sr-queue-list');",
  "    if (!list) return;",
  "    const all = (st.current ? [st.current] : []).concat(st.queue || []);",
  "    if (!all.length) { list.innerHTML = '<div class=\\\"sr-empty\\\">No songs in the queue — viewers type !play in chat 🎧</div>'; return; }",
  "    let startIn = 0;",
  "    list.innerHTML = all.map((q, i) => {",
  "      const now = i === 0 && q.startedAt;",
  "      const elapsed = now ? Math.min(Date.now() - q.startedAt, q.durationMs || 0) : 0;",
  "      let line;",
  "      if (now) { line = '<span class=\\\"now-tag\\\">NOW </span>' + fmt(elapsed) + ' / ' + fmt(q.durationMs || 0); startIn = Math.max(0, (q.durationMs || 0) - elapsed); }",
  "      else { line = 'Starts in ' + fmt(startIn) + ' • ' + esc(q.requestedBy || ''); startIn += q.durationMs || 0; }",
  "      return '<div class=\\\"sr-q' + (now ? ' now' : '') + '\\\">'",
  "        + (q.artwork ? '<img src=\\\"' + esc(q.artwork) + '\\\" alt=\\\"\\\">' : '')",
  "        + '<div class=\\\"sr-q-info\\\"><div class=\\\"sr-q-t\\\">' + esc(q.title) + ' — ' + esc(q.artist || '') + '</div><div class=\\\"sr-q-s\\\">' + line + '</div></div>'",
  "        + '<button class=\\\"btn btn-danger btn-sm\\\" data-sr-del=\\\"' + esc(q.id) + '\\\" title=\\\"Remove\\\">✕</button>'",
  "        + '</div>';",
  "    }).join('');",
  "    list.querySelectorAll('[data-sr-del]').forEach((b) =>",
  "      b.addEventListener('click', async () => { await srReq('POST', 'remove', { id: b.dataset.srDel }); srRefresh(); }));",
  "  }",
  "",
  "  function srApply(st) {",
  "    if (!st) return;",
  "    srState = st;",
  "    renderQueue(st);",
  "    const sc = $('sr-sc-status');",
  "    if (sc) {",
  "      sc.textContent = st.searchAvailable ? 'Connected ✓ — search & playback ready' : 'Unavailable ✗ — SoundCloud not reachable';",
  "      sc.className = 'sr-sc ' + (st.searchAvailable ? 'ok' : 'fail');",
  "    }",
  "    const stateEl = $('sr-state');",
  "    if (stateEl) {",
  "      stateEl.textContent = st.settings && st.settings.enabled ? 'Online' : 'Offline';",
  "      stateEl.style.color = st.settings && st.settings.enabled ? '#57a273' : '#d97a74';",
  "    }",
  "  }",
  "",
  "  async function srRefresh() {",
  "    try { srApply(await srReq('GET', 'state')); } catch (e) {}",
  "  }",
  "",
  "  function fillSettings(s) {",
  "    if (!s) return;",
  "    const map = {",
  "      'sr-enabled': s.enabled !== false,",
  "      'sr-play-enabled': s.playEnabled !== false,",
  "      'sr-play-cost': s.playCost ?? 0,",
  "      'sr-skip-enabled': s.skipEnabled !== false,",
  "      'sr-skip-cost': s.skipCost ?? 1,",
  "      'sr-allow-skip-own': s.allowSkipRequested !== false,",
  "      'sr-allow-explicit': s.allowExplicit !== false,",
  "      'sr-max-queue': s.maxQueue ?? 20,",
  "      'sr-max-user': s.maxQueuePerUser ?? 2,",
  "      'sr-permanent': s.overlayPermanent !== false,",
  "      'sr-volume': s.volume ?? 80,",
  "      'sr-scale': s.overlayScale ?? 100,",
  "      'sr-points': s.pointsPerMessage ?? 1,",
  "    };",
  "    for (const [id, val] of Object.entries(map)) {",
  "      const el = $(id);",
  "      if (!el) continue;",
  "      if (el.type === 'checkbox') el.checked = !!val;",
  "      else { el.value = val; el.dispatchEvent(new Event('input')); }",
  "    }",
  '    const fb = $("sr-fallback"); if (fb) fb.value = s.fallbackUrl || "";',
  '    const ra = $("sr-roles-all"); if (ra) ra.checked = (s.allowedFor || {}).all !== false;',
  '    const rs = $("sr-roles-subs"); if (rs) rs.checked = !!(s.allowedFor || {}).subs;',
  '    const rm = $("sr-roles-mods"); if (rm) rm.checked = (s.allowedFor || {}).mods !== false;',
  '    const cp = $("sr-cmd-play"); if (cp) cp.textContent = s.playCmd || "!play";',
  '    const cs = $("sr-cmd-skip"); if (cs) cs.textContent = s.skipCmd || "!skip";',
  "  }",
  "",
  "  async function loadSettings() {",
  "    try { const r = await srReq('GET', 'settings'); if (r && r.settings) fillSettings(r.settings); } catch (e) {}",
  "  }",
  "",
  "  async function loadHistory() {",
  "    try {",
  "      const q = ($('sr-hist-search') || {}).value || '';",
  "      const r = await srReq('GET', 'history?q=' + encodeURIComponent(q));",
  "      const body = $('sr-hist-body');",
  "      if (!body) return;",
  "      const hist = (r && r.history) || [];",
  "      if (!hist.length) { body.innerHTML = '<tr><td colspan=\\\"4\\\" style=\\\"text-align:center;padding:20px;color:var(--text-muted,#6d6960)\\\">No data</td></tr>'; return; }",
  "      body.innerHTML = hist.map((h) =>",
  "        '<tr><td>' + esc(new Date(h.date).toLocaleString('en-GB')) + '</td>'",
  "        + '<td style=\\\"direction:ltr;text-align:left\\\">' + esc(h.user) + '</td>'",
  "        + '<td style=\\\"font-weight:700\\\">' + esc(h.track) + '</td>'",
  "        + '<td class=\\\"st-' + esc(h.status) + '\\\">' + esc(h.status) + '</td></tr>'",
  "      ).join('');",
  "    } catch (e) {}",
  "  }",
  "",
  "  // ===== الربط =====",
  "  const vol = $('sr-volume'), volVal = $('sr-volume-val');",
  "  if (vol && volVal) vol.addEventListener('input', () => (volVal.textContent = vol.value));",
  "  const scale = $('sr-scale'), scaleVal = $('sr-scale-val');",
  "  if (scale && scaleVal) scale.addEventListener('input', () => (scaleVal.textContent = scale.value + '%'));",
  "",
  "  const ctrl = async (action) => { await srReq('POST', 'control', { action }); };",
  "  const bp = $('sr-pause'), br = $('sr-resume'), brs = $('sr-restart');",
  "  if (bp) bp.addEventListener('click', () => ctrl('pause'));",
  "  if (br) br.addEventListener('click', () => ctrl('resume'));",
  "  if (brs) brs.addEventListener('click', () => ctrl('restart'));",
  "",
  "  const saveBtn = $('sr-save');",
  "  if (saveBtn) saveBtn.addEventListener('click', async () => {",
  "    const settings = {",
  "      enabled: ($('sr-enabled') || {}).checked !== false,",
  "      playEnabled: ($('sr-play-enabled') || {}).checked !== false,",
  "      playCost: parseInt(($('sr-play-cost') || {}).value, 10) || 0,",
  "      skipEnabled: ($('sr-skip-enabled') || {}).checked !== false,",
  "      skipCost: parseInt(($('sr-skip-cost') || {}).value, 10) || 0,",
  "      allowSkipRequested: ($('sr-allow-skip-own') || {}).checked !== false,",
  "      allowExplicit: ($('sr-allow-explicit') || {}).checked !== false,",
  "      maxQueue: parseInt(($('sr-max-queue') || {}).value, 10) || 20,",
  "      maxQueuePerUser: parseInt(($('sr-max-user') || {}).value, 10) || 2,",
  "      overlayPermanent: ($('sr-permanent') || {}).checked !== false,",
  "      volume: Math.max(0, Math.min(100, parseInt(($('sr-volume') || {}).value, 10) || 80)),",
  "      overlayScale: Math.max(40, Math.min(200, parseInt(($('sr-scale') || {}).value, 10) || 100)),",
  '      fallbackUrl: (($("sr-fallback") || {}).value || "").trim(),',
  "      pointsPerMessage: parseInt(($('sr-points') || {}).value, 10) || 0,",
  "      allowedFor: {",
  "        all: ($('sr-roles-all') || {}).checked !== false,",
  "        subs: ($('sr-roles-subs') || {}).checked !== false,",
  "        mods: ($('sr-roles-mods') || {}).checked !== false,",
  "      },",
  "    };",
  "    const r = await srReq('POST', 'settings', settings);",
  "    const msg = $('sr-save-msg');",
  "    if (msg) {",
  "      msg.textContent = r && r.ok ? '✅ Saved — applied instantly to the overlay' : '⚠ Save failed' + (r && r.error ? ' — ' + r.error : '');",
  "      msg.className = 'msg ' + (r && r.ok ? 'ok' : 'bad');",
  "    }",
  "    srRefresh();",
  "  });",
  "",
  "  const testBtn = $('sr-test-add');",
  "  if (testBtn) testBtn.addEventListener('click', async () => {",
  "    const q = ($('sr-test-name') || {}).value.trim();",
  "    const msg = $('sr-test-msg');",
  "    if (!q) { if (msg) { msg.textContent = 'Type a song name first'; msg.className = 'msg bad'; } return; }",
  "    if (msg) { msg.textContent = 'Searching SoundCloud...'; msg.className = 'msg info'; }",
  "    const r = await srReq('POST', 'test', { query: q });",
  "    if (r && r.ok) {",
  "      if (msg) { msg.textContent = '✅ Added: ' + ((r.track || {}).title || ''); msg.className = 'msg ok'; }",
  "      $('sr-test-name').value = '';",
  "      srRefresh();",
  "    } else if (msg) { msg.textContent = '⚠ ' + ((r && r.error) || 'failed'); msg.className = 'msg bad'; }",
  "  });",
  "",
  "  const skipNow = $('sr-skip-now');",
  "  if (skipNow) skipNow.addEventListener('click', async () => { await srReq('POST', 'skip'); srRefresh(); });",
  "  const clearBtn = $('sr-clear');",
  "  if (clearBtn) clearBtn.addEventListener('click', async () => { await srReq('POST', 'clear'); srRefresh(); });",
  "  const histSearch = $('sr-hist-search');",
  "  if (histSearch) histSearch.addEventListener('input', loadHistory);",
  "",
  "  // لينك الأوفرلاي على الدومين بتاعك",
  "  (async () => {",
  "    try {",
  "      const info = await api.overlay.getInfo();",
  "      const base = (info && info.base) || '';",
  "      const el = $('sr-ov-url');",
  "      if (el && base) el.value = base + '/overlay-music.html';",
  "      const cp = $('sr-ov-copy');",
  "      if (cp) cp.addEventListener('click', () => {",
  "        navigator.clipboard.writeText(el.value).then(() => { cp.textContent = '✅ Copied'; setTimeout(() => (cp.textContent = '📋 Copy Overlay URL'), 2000); });",
  "      });",
  "    } catch (e) {}",
  "  })();",
  "",
  "  loadSettings();",
  "  srRefresh();",
  "  loadHistory();",
  "  srPoll = setInterval(() => { srRefresh(); }, 3000);",
  "})();",
].join("\n");

s = s.slice(0, start) + block + "\n" + s.slice(start + startMarker.length);
fs.writeFileSync("src/renderer.js", s);
console.log("native SR renderer block installed ✓");
